# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='enrolled_courses',
        ),
        migrations.AlterField(
            model_name='course',
            name='participant',
            field=models.ManyToManyField(blank=True, related_name='enrolled_courses', to='api.Participant'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='completed_components',
            field=models.ManyToManyField(blank=True, related_name='completed_participants', to='api.Component'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_participants', to='api.Course'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='completed_modules',
            field=models.ManyToManyField(blank=True, related_name='completed_participants', to='api.Module'),
        ),
        migrations.AlterField(
            model_name='user',
            name='as_instructor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Instructor'),
        ),
        migrations.AlterField(
            model_name='user',
            name='as_participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.Participant'),
        ),
        migrations.AddField(
            model_name='user',
            name='as_administrator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Administrator'),
        ),
    ]
