# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161119_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='down the Magical Mysteral Penny lane lol'),
            preserve_default=False,
        ),
    ]
