# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 04:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='You must give a username', regex='.')]),
        ),
    ]
