# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-03 10:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20161121_0420'),
    ]

    operations = [
        migrations.CreateModel(
            name='HR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='You must give a username', regex='.')])),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='files',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='videos',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
